title: Wang Nan 's Homepage
description: NONE
url: https://wangnan.net
lang: zh

owner:
  name: Wang Nan
  avatar: hanlin.jpg (根目录下的图片)
  email: me@wangnan.net
  github: theFool-wn
  # cv: /assets/files/xxx.pdf
  # scholar: ...
  
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
