include:
  - _pages
title: Wang Nan 's Homepage
description: Have a nice day!
url: https://wangnan.net
lang: en
logo: /assets/image/logo.jpg
show_downloads: false
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
theme: jekyll-theme-minimal

owner:
  name: Wang Nan
  # avatar: /assets/image/wangnan.png
  email: me@wangnan.net
  github: theFool-wn
  cv: /assets/files/resume.pdf
  # scholar: ...
  
