title: Wang Nan 's Homepage
description: NONE
url: https://wangnan.net
lang: zh

owner:
  name: Wang Nan
  avatar: hanlin.jpg (根目录下的图片)
  email: me@wangnan.net
  github: theFool-wn
  linkedin: hanlin-cai-07b53b23b（只需要ID即可）
